config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/menu')

  get "/menu", to: "menu#today", as: "menu"

  resources :orders, only: [:create]
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  has_many :orders

  def total_ordered
    total_ordered = 0

    #Aggregate total quantity ordered by each person
    self.orders.group(:email).each do |order|
      total_ordered += order.quantity
    end

    total_ordered
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :dish
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit(:name, :desc, :ingredients, :calories, :protein, :sodium, :carbs, :price)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  before_action :set_dish, only: [:today]

  def today
    @dish
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @dish = Dish.last
    end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    order = Order.new(order_params)
    if order.save
      render text:  "Thank you for your order.  If you would like to cancel / modify your order, please reply back to the confirmation email that was just sent."
    else
      render text:  "Failed"
    end
  end


  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(
        :dish_id,
        :quantity,
        :first,
        :last,
        :email,
        :phone,
        :deliver_to)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_show.html.haml
%p#notice= notice

%p
  = image_tag @dish.img_url
%p
  %b Name:
  = @dish.name
%p
  %b Desc:
  = @dish.desc
%p
  %b Ingredients:
  = @dish.ingredients
%p
  %b Calories:
  = @dish.calories
%p
  %b Protein:
  = @dish.protein
%p
  %b Sodium:
  = @dish.sodium
%p
  %b Carbs:
  = @dish.carbs
%p
  %b Price:
  = @dish.price

%p
  %b Total ordered:
  = @dish.total_ordered

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Peekadish
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/menu/today.html.haml
= render partial: 'dishes/show'

= render partial: 'orders/form'

app/views/orders/_form.html.haml
= form_for :order, {url: orders_path} do |f|
  = f.hidden_field :dish_id, value: @dish.id

  First name: #{f.text_field :first}
  %br/

  Last name : #{f.text_field :last}
  %br/

  Email : #{f.text_field :email}
  %br/

  Phone: #{f.text_field :phone}
  %br/

  Quantity: #{f.select :quantity, [0, 1, 2, 3]}
  %br/

  Deliver to: #{f.select :deliver_to, ["Netflix", "Google"]}
  %br/

  = f.submit